updated dashboard logic

diff --git a/.github/workflows/regenerate-meetings-and-videos.yml b/.github/workflows/regenerate-meetings-and-videos.yml
--- a/.github/workflows/regenerate-meetings-and-videos.yml
+++ b/.github/workflows/regenerate-meetings-and-videos.yml
@@ -34,8 +34,13 @@ jobs:
         - name: Install dependencies
           run: npm install
 
-        - name: Regenerate
-          run: npm run generate:meetings && npm run generate:videos && npm run generate:dashboard
+        - name: Regenerate meetings and videos
+          run: |
+            npm run generate:meetings
+            npm run generate:videos
+
+        - name: Regenerate dashboard
+          run: npm run generate:dashboard || echo "::warning::Dashboard generation failed, continuing with available data"
 
         - name: Create Pull Request with new meetings.json, newsroom-videos.json and dashboard.json version
           uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # use 4.2.4 https://github.com/peter-evans/create-pull-request/releases/tag/v4.2.4
